version: "3.7"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: waha_server_1
      APP_PORT: 3000
      WHATSAPP_DEFAULT_ENGINE: NOWEB
      WHATSAPP_HOOK_EVENTS: message
      
      # If you are going to use the Waha integrated with the N8n (https://waha-n8n-templates.devlike.pro/) 
      # Uncomment the line below and replace the url with your n8n node production url
      #WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/our-webhook-id-from-n8n-waha-node/waha 
     
    container_name: waha_app_proxy_1
  server:
    image: devlikeapro/waha:arm
    restart: on-failure
    volumes:
        - ${APP_DATA_DIR}/data:/tmp
    init: true
    # The format here is: <app-id>_<docker-service-name>_1
    container_name: waha_server_1
